# Use Python 3.10 slim version
FROM python:3.10-slim

# Update the package manager and install system dependencies
RUN apt-get update && apt-get install -y \
    gcc

# Set the working directory
WORKDIR /app

# Copy project files into the container
COPY . .

# Upgrade pip
RUN pip install --upgrade pip

# Install dependencies from requirements.txt
RUN pip install -r requirements.txt

# Expose the port Flask runs on
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
